module.exports = {
    REGION_MAP: {
        "Isle of Man": "IM",
        "Croatia": "HR",
        "Guinea-Bissau": "GW",
        "India": "IN",
        "Kenya": "KE",
        "Laos": "LA",
        "British Indian Ocean Territory": "IO",
        "Haiti": "HT",
        "Lebanon": "LB",
        "Guyana": "GY",
        "Kyrgyzstan": "KG",
        "Hungary": "HU",
        "St.Lucia": "LC",
        "Iraq": "IQ",
        "Kampuchea (Cambodia )": "KH",
        "Jamaica": "JM",
        "Kiribati": "KI",
        "Iceland": "IS",
        "Morocco": "MA",
        "Jordan": "JO",
        "Italy": "IT",
        "Japan": "JP",
        "Monaco": "MC",
        "Comoros": "KM",
        "Moldova, Republic of": "MD",
        "Liechtenstein": "LI",
        "St. Kitts & Nevis": "KN",
        "Montenegro": "ME",
        "Namibia": "NA",
        "St. Martin": "MF",
        "Sri Lanka": "LK",
        "Madagascar": "MG",
        "New Caledonia": "NC",
        "Marshall Islands": "MH",
        "Korea": "KR",
        "Niger": "NE",
        "Norfolk Island": "NF",
        "North Macedonia": "MK",
        "Nigeria": "NG",
        "Mali": "ML",
        "Myanmar (Burma)": "MM",
        "Liberia": "LR",
        "Nicaragua": "NI",
        "Kuwait": "KW",
        "Mongolia": "MN",
        "Lesotho": "LS",
        "Panama": "PA",
        "Macao": "MO",
        "Lithuania": "LT",
        "Cayman Is.": "KY",
        "Northern Mariana Islands": "MP",
        "Luxembourg": "LU",
        "Netherlands": "NL",
        "Kazakhstan": "KZ",
        "Martinique": "MQ",
        "Latvia": "LV",
        "Mauritania": "MR",
        "Peru": "PE",
        "Montserrat": "MS",
        "Qatar": "QA",
        "Norway": "NO",
        "French Polynesia": "PF",
        "Malta": "MT",
        "Libya": "LY",
        "Nepal": "NP",
        "Papua New Cuinea": "PG",
        "Mauritius": "MU",
        "Philippines": "PH",
        "Maldives": "MV",
        "Oman": "OM",
        "Nauru": "NR",
        "Malawi": "MW",
        "Mexico": "MX",
        "Pakistan": "PK",
        "Malaysia": "MY",
        "Niue": "NU",
        "Poland": "PL",
        "Mozambique": "MZ",
        "St. Pierre & Miquelon": "PM",
        "Pitcairn Islands": "PN",
        "Réunion": "RE",
        "Saudi Arabia": "SA",
        "Solomon Is": "SB",
        "New Zealand": "NZ",
        "Seychelles": "SC",
        "Sudan": "SD",
        "Puerto Rico": "PR",
        "Sweden": "SE",
        "Palestinian Territories": "PS",
        "Portugal": "PT",
        "Singapore": "SG",
        "Turks & Caicos Islands": "TC",
        "Ascension Island": "SH",
        "Chad": "TD",
        "Slovenia": "SI",
        "Palau": "PW",
        "Svalbard & Jan Mayen": "SJ",
        "Ukraine": "UA",
        "Romania": "RO",
        "Slovakia": "SK",
        "Paraguay": "PY",
        "Togo": "TG",
        "Sierra Leone": "SL",
        "Thailand": "TH",
        "San Marino": "SM",
        "Senegal": "SN",
        "Serbia": "RS",
        "Tajikstan": "TJ",
        "Vatican City": "VA",
        "Somali": "SO",
        "Tokelau": "TK",
        "Uganda": "UG",
        "Russia": "RU",
        "Timor-Leste": "TL",
        "St. Vincent & Grenadines": "VC",
        "Turkmenistan": "TM",
        "Suriname": "SR",
        "Rwanda": "RW",
        "Tunisia": "TN",
        "Venezuela": "VE",
        "South Sudan": "SS",
        "Tonga": "TO",
        "Sao Tome and Principe": "ST",
        "British Virgin Islands": "VG",
        "EI Salvador": "SV",
        "Turkey": "TR",
        "U.S. Virgin Islands": "VI",
        "Sint Maarten": "SX",
        "Wallis & Futuna": "WF",
        "Trinidad & Tobago": "TT",
        "Eswatini": "SZ",
        "Tuvalu": "TV",
        "Taiwan": "TW",
        "Vietnam": "VN",
        "United States": "US",
        "Tanzania": "TZ",
        "Yemen": "YE",
        "South Africa": "ZA",
        "Kosovo": "XK",
        "Uruguay": "UY",
        "Vanuatu": "VU",
        "Uzbekistan": "UZ",
        "Samoa": "WS",
        "Zambia": "ZM",
        "Andorra": "AD",
        "Mayotte": "YT",
        "United Arab Emirates": "AE",
        "Bosnia & Herzegovina": "BA",
        "Afghanistan": "AF",
        "Barbados": "BB",
        "Antigua & Barbuda": "AG",
        "Bangladesh": "BD",
        "Anguilla": "AI",
        "Belgium": "BE",
        "Canada": "CA",
        "Burkina-faso": "BF",
        "Bulgaria": "BG",
        "Zimbabwe": "ZW",
        "Albania": "AL",
        "Cocos (Keeling) Islands": "CC",
        "Bahrain": "BH",
        "Armenia": "AM",
        "Congo - Kinshasa": "CD",
        "Burundi": "BI",
        "Benin": "BJ",
        "Angola": "AO",
        "Central African Republic": "CF",
        "Congo - Brazzaville": "CG",
        "St. Barthélemy": "BL",
        "Switzerland": "CH",
        "Bermuda": "BM",
        "Argentina": "AR",
        "Ivory Coast": "CI",
        "Brunei": "BN",
        "Germany": "DE",
        "American Samoa": "AS",
        "Bolivia": "BO",
        "Austria": "AT",
        "Cook Is.": "CK",
        "Diego Garcia": "DG",
        "Australia": "AU",
        "Chile": "CL",
        "Ecuador": "EC",
        "Caribbean Netherlands": "BQ",
        "Cameroon": "CM",
        "Brazil": "BR",
        "Aruba": "AW",
        "China mainland": "CN",
        "Estonia": "EE",
        "Bahamas": "BS",
        "Djibouti": "DJ",
        "Åland Islands": "AX",
        "Colombia": "CO",
        "Bhutan": "BT",
        "Denmark": "DK",
        "Egypt": "EG",
        "Azerbaijan": "AZ",
        "Western Sahara": "EH",
        "Dominica": "DM",
        "Costa Rica": "CR",
        "Botswana": "BW",
        "Gabon": "GA",
        "Dominica Rep.": "DO",
        "Belarus": "BY",
        "United Kingdom": "UK",
        "Belize": "BZ",
        "Cape Verde": "CV",
        "Grenada": "GD",
        "Finland": "FI",
        "Curaçao": "CW",
        "Georgia": "GE",
        "Fiji": "FJ",
        "Christmas Island": "CX",
        "French Guiana": "GF",
        "Falkland Islands": "FK",
        "Cyprus": "CY",
        "Guernsey": "GG",
        "Czechia": "CZ",
        "Ghana": "GH",
        "Micronesia": "FM",
        "Eritrea": "ER",
        "Gibraltar": "GI",
        "Spain": "ES",
        "Faroe Islands": "FO",
        "Ethiopia": "ET",
        "Greenland": "GL",
        "Algeria": "DZ",
        "Gambia": "GM",
        "Indonesia": "ID",
        "France": "FR",
        "Guinea": "GN",
        "Ireland": "IE",
        "Hongkong": "HK",
        "Guadeloupe": "GP",
        "Equatorial Guinea": "GQ",
        "Greece": "GR",
        "Honduras": "HN",
        "Jersey": "JE",
        "So. Georgia & So. Sandwich  Isl.": "GS",
        "Guatemala": "GT",
        "Guam": "GU",
        "Israel": "IL"
    }
}
